language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t studypurpose/docker-react -f Dockerfile .

script:
  - docker run -e CI=true studypurpose/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  name: 'docker-react'
  env: 'DockerReact-env'
  bucket_name: 'elasticbeanstalk-us-east-1-863890899320'
  bucket_path: 'docker-react'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
